### ISSUE TITLE
Menu buttons on new tab page displayed as grey boxes

### ISSUE THREAD

**Issue by Mrfiregem** [Guerra24/Firefox-UWP-Style#10]
This affects the menu buttons for each module, pinned sites, etc. That may be as intentioned, however it also affects the search bar's "search" button.
![image](https://user-images.githubusercontent.com/5158194/44375372-5cf4f180-a4c1-11e8-8ce2-c1f164fc522f.png)

**Comment by Guerra24** [comment]
Made a quick fix, I've already spend too much time working on the `about:*` pages.

The proper fix for this is a re-style from scratch since the current code was never created to work with the new userChrome styles.

**Comment by Guerra24** [comment]
New style for the new tab page.

![img](https://puu.sh/BiosO/2f8d221a15.gif)
