### ISSUE TITLE
Extensions affected by style

### ISSUE THREAD

**Issue by Mrfiregem** [Guerra24/Firefox-UWP-Style#11]
When using this theme, certain extensions have graphics or overlays blocked out. You may not bother with fixing these, but I'll post here since they are pretty popular extensions. First, uBlock Origin's *element picker* overlay is completely black, preventing you from viewing your selection, eg.,  
Without the style:
![firefox_2018-10-23_14-51-35](https://user-images.githubusercontent.com/5158194/47384197-6d4d6680-d6d4-11e8-83ea-db1627ac9883.png)

With the style:
![firefox_2018-10-23_14-52-47](https://user-images.githubusercontent.com/5158194/47384223-7e967300-d6d4-11e8-91bd-c16d87842e72.png)

Using S3.Translator results in its popup's button icons turning into black squares.

Lastly, this (from Protonmail's website) and presumably other iframes inherit a black background color if none is provided, making the text difficult to read without modifying it using a userstyle or other means
![firefox_2018-10-23_15-05-21](https://user-images.githubusercontent.com/5158194/47384514-62df9c80-d6d5-11e8-8431-aae738f4df0d.png)

**Comment by Guerra24** [comment]
Firefox uses iframes to display the addons UI, it treats them as `about:blank` thus falling into the `@-moz-document url-prefix("chrome://"), url-prefix("about:")` selector.

Using `regexp("about:(?!blank).*")` I was able to exclude the `about:blank` page, this should fix any issue with addons and iframes in pages (I hope 🙏 ).
