### ISSUE TITLE
Reading mode sidebar misstyled

### ISSUE THREAD

**Issue by Mrfiregem** [Guerra24/Firefox-UWP-Style#12]
The settings bar for reading mode has it's buttons squished up to the top. The sidebar itself is also white, when I think it should be styled darker to fit the theme.
![image](https://user-images.githubusercontent.com/5158194/47464133-4cf5d880-d7b6-11e8-990e-0e3f6a8b24d8.png)

**Comment by Guerra24** [comment]
Update on this: Right now I'm busy with the final project of the semester and other related stuff so I will continue next week, I already did some work but still needs some tweaks.

**Comment by Guerra24** [comment]
![gif](https://puu.sh/BWWPc/26f2f12862.gif)
