### ISSUE TITLE
Implement Light color theme

### ISSUE THREAD

**Issue by Guerra24** [Guerra24/Firefox-UWP-Style#13]
This requires separating the color rules into a `light.css` and `dark.css` files, something like this:

- [x] tags-dark.css
- [x] tags-light.css
- [x] base-dark.css
- [x] base-light.css
- [x] context-dark.css
- [x] context-light.css
- [x] pagesContent-dark.css
- [x] pagesContent-light.css
- [x] pagesChrome-dark.css
- [x] pagesChrome-light.css

Only color rules will be separated. Also needs special handling for the scrollbars and forced tooltips.

The Light theme will be based on the 19H1's colors and only target Firefox 65+ due to more compatibility with Nightly's rules.

**Comment by maicol07** [comment]
Waiting this! 👍🏻

**Comment by Guerra24** [comment]
Light theme has been available for a while but is not 100% finished due to dev toolbox being a pain to work with. Made some changes in the latest commit that fixes color issues. I will keep this open until it is properly finished, no ETA for that but feel free to report any issues.

// @maicol07
