### ISSUE TITLE
Allow changing sidebar width

### ISSUE THREAD

**Issue by Mrfiregem** [Guerra24/Firefox-UWP-Style#15]
The width set by this style is good for extensions like tree tabs, but is way too small for some others. I suggest re-adding sizing the sidebar to compensate.

**Comment by Guerra24** [comment]
Adding to the commit message... I accidentally removed the resizing feature when trying to change the border and somehow that wasn't reported before and I didn't notice it 😅

**Comment by Mrfiregem** [comment]
I was surprised to see it gone. I never noticed it either until I tried a new extension today lol

**Comment by rocco-xyz** [comment]
I made a small modification to increase the width of the scroll bar (to 22px).
Change the contents of the file **custom_scrollbars.uc.js** (inside **\<YourProfile\>**\chrome\js) to this:
[https://pastebin.com/dzmnTgnV](https://pastebin.com/dzmnTgnV) (sorry I'm new to GitHub and I'm learning how to use it)
To be effective, delete the contents of the **startupCache** folder and restart Firefox.
The **startupCache** folder is in %LOCALAPPDATA%\Mozilla\Firefox\Profiles\\**\<YourProfile\>**
and **it's a different folder** than
%APPDATA%\Mozilla\Firefox\Profiles\\**\<YourProfile\>**
