### ISSUE TITLE
The "List all tabs" button is only visible while hovered.

### ISSUE THREAD

**Issue by rocco-xyz** [Guerra24/Firefox-UWP-Style#17]
![List all tabs button](https://i.imgur.com/umsWnRZ.png)
And its icon should be replaced for **./img/arrowdown.png**

**Comment by Guerra24** [comment]
Can't reproduce on Nightly(68) and Stable(66).

![img](https://puu.sh/Dtn7b/918334f42a.png)

Also, the All Tabs button only appears when the tabs overflow the tab bar but that doesn't seems the case, I don't see any overflow scroll buttons. Is there any extra css-code that causes that? Or maybe the density setting, the theme only supports the compact mode.

**Comment by rocco-xyz** [comment]
I do not know exactly what happened, reapplying the dark theme fixed the problem.
Sorry.

**Comment by Guerra24** [comment]
No problem, in that case I'm closing this. If the issue repeats just reopen and I'll take a look.
