### ISSUE TITLE
No back button on YouTube's settings popup

### ISSUE THREAD

**Issue by Srini-B** [Guerra24/Firefox-UWP-Style#20]
![Untitled](https://user-images.githubusercontent.com/22414119/78955035-9f869a00-7afb-11ea-8a34-3d5e93b6e213.png)

as you can see no back button on top left

**Comment by Guerra24** [comment]
Style does not affect regular pages. Still tested with both old and new youtube, button still there.

Unless somehow youtube is going through the regexp I don't see how that might happen. If you're using Stylus make sure no other style is affecting youtube or any extension.

If you are sure the style is causing that, please let me know the version of Firefox and (if any) extensions used, I will take a look.

![image](https://user-images.githubusercontent.com/9023392/78955503-ac27d580-7a9c-11ea-913f-80cb7cefd580.png) 
![image](https://user-images.githubusercontent.com/9023392/78955560-d4afcf80-7a9c-11ea-86e2-e19bc880b9a3.png)

**Comment by Srini-B** [comment]
Disabling Midnight Lizard and refreshing brought it back. 

Thanks
