### ISSUE TITLE
Broken home tab on Firefox 73

### ISSUE THREAD

**Issue by danirod** [Guerra24/Firefox-UWP-Style#21]
A picture is better than a thousand words.

![imagen](https://user-images.githubusercontent.com/1568690/80767727-decb6800-8b48-11ea-828e-de5763523455.png)

It is happening in the about:newtab page.

**Comment by Guerra24** [comment]
Fixed, buttons and colors should display correctly.

![image](https://user-images.githubusercontent.com/9023392/80775249-5636d280-8b1c-11ea-86b7-3c5d3d343c06.png)
