### ISSUE TITLE
Guerra24 / Firefox-UWP-Style how do you change address and bookmark bars size

### ISSUE THREAD

**Issue by mattson718** [Guerra24/Firefox-UWP-Style#23]
address and bookmark bars are to big how do you change there size and text size is menus is to small 
![address and bookmarkbar ](https://user-images.githubusercontent.com/71533120/93654166-0a080400-f9d1-11ea-9db8-b6c6e77e5690.png)

**Comment by Guerra24** [comment]
Search bar is broken, gonna fix it when I have free time. I'm not sure what could cause bookmarks to be that big, maybe hidpi issue? all text is too big.
