### ISSUE TITLE
some thing is wrong with text size

### ISSUE THREAD

**Issue by mattson718** [Guerra24/Firefox-UWP-Style#24]
![text size](https://user-images.githubusercontent.com/71533120/93655345-a8976380-f9d7-11ea-92cb-c2a8178b243b.png)
![text size 2](https://user-images.githubusercontent.com/71533120/93655347-ac2aea80-f9d7-11ea-8fb4-83bdae8384d2.png)
![test size 3](https://user-images.githubusercontent.com/71533120/93655352-afbe7180-f9d7-11ea-95e8-58806e57f958.png)
![text size 4](https://user-images.githubusercontent.com/71533120/93655355-b220cb80-f9d7-11ea-9b30-da818ea4e284.png)

**Comment by mattson718** [comment]
![text size 5](https://user-images.githubusercontent.com/71533120/93655474-67538380-f9d8-11ea-91bc-8cf8c7554f6d.png)

**Comment by Guerra24** [comment]
Thing is there are no changes in the text size, it uses whatever Firefox defaults to. Are you sure there are no about:config changes? using scaling in Windows?

**Comment by Guerra24** [comment]
Closing because no more info info was provided.
