### ISSUE TITLE
Adress Bar Selection Color

### ISSUE THREAD

**Issue by IBArbitrary** [Guerra24/Firefox-UWP-Style#25]
The address bar selection colour is same as the address bar, and this makes it difficult when mouse-over focus is not over the address-bar, e.g. while using suggestions in the address bar.

When the mouse-over focus is off:
![focus off](https://user-images.githubusercontent.com/57673410/104816828-93c2c380-5843-11eb-9736-2513750b8b6e.png)
When the mouse-over focus is on:
![focus on](https://user-images.githubusercontent.com/57673410/104816842-ae953800-5843-11eb-925b-bdf292a9f794.png)

**Comment by Guerra24** [comment]
Selection color is based on the accent color. Nothing I can do.

**Comment by IBArbitrary** [comment]
Right. My bad.
