### ISSUE TITLE
Tab Animations

### ISSUE THREAD

**Issue by IBArbitrary** [Guerra24/Firefox-UWP-Style#26]
Tab-Bar animations seem to be turned off. My system has animations turned on, but the tab open/close animations and the tab load animations are not working.

Example, the static load symbol instead of the oscillating dot:
![image](https://user-images.githubusercontent.com/57673410/104816924-3ed37d00-5844-11eb-8897-9615113ed1e8.png)

**Comment by Guerra24** [comment]
Theme does not change any animations or preferences. Make sure `ui.prefersReducedMotion` is set to `0` to allow animations.

**Comment by IBArbitrary** [comment]
@Guerra24 That solved it, thanks for the heads up. Was not an issue, but my ignorance, closing it thus.
