### ISSUE TITLE
Minor changes to allow for customisation

### ISSUE THREAD

**Issue by xcasxcursex** [Guerra24/Firefox-UWP-Style#27]
Hi there,

Before I go on, thanks for this theme. I had been enjoying ShadowFox but since it's been unmaintained I went looking for an alternative, and am loving this. 

I wanted to make a few customisations to the theme (eg. setting normal UWP toolbar heights rather than the oversized firefox default heights) but I don't want to do it in a way that I can't easily update the theme from here, at a later date, should you make any changes. Since you're using @import rules, that's pretty straightforward and this would be the first of the suggestions I'd like to make: place an @import rule to a user-modifiable file which would be missing in this repo but could be created by an individual.

There is one issue with that though: the root vars. In order to override these, which for many may just be a preference but is a necessity for me because my accent colour is black and I get a lot of black-on-black elements (an issue that UWP apps solve by overriding the accent colour to a dark shade of grey) the user customisation must occur after the theme-default vars are defined, but because you are using @import rules, they must precede all other rules including these definitions. The solution to this is simple: set the root vars in the top of the base.css/context.css files, instead. This would be my second suggestion.

If there's any interest in this I'd be happy to submit a PR, although perhaps you'd find it more straightforward to take care of it since it's two lines of code and two cut'n'pastes?

Cheers!

**Comment by Guerra24** [comment]
Hey! Sure, added a new css for chrome and content overrides. I tested overriding vars from said css and it works with non-important ones so you can change all of the theme defined vars but changing firefox ones directly will not work if those use !important.

Check if the change is working for your needs and let me know if it works or needs changes.

**Comment by xcasxcursex** [comment]
That works - it's literally word for word case sensitive exactly what I wrote here. Not only are you blindingly fast but apparently also psychic ;)

Thanks mate!

**Comment by Guerra24** [comment]
@xcasxcursex Hey, just a heads up... Nightly changed how the accent color is set breaking 95% of the rules. I'll be replacing the var with the property itself. So with 88+ if you want to change the accent color create two new prefs.

`ui.-moz-accent-color=#FF00FF` 
`ui.-moz-accent-color-foreground=#FFFFFF`

Both strings set to RGB Hex values. Foreground sets the text color when the background is the accent color.

**Comment by xcasxcursex** [comment]
Thanks mate! Kind of you to think of me!
Nightly is definitely a moving target right now. I think we'll be tinkering with this some more, but I've noticed your theme has been quite resilient so far! Hang in there :)
