### ISSUE TITLE
url bar off center when search bar is present

### ISSUE THREAD

**Issue by yhnmj6666** [Guerra24/Firefox-UWP-Style#28]
hello, i'm using firefox 89.0.
when search bar is enabled: 
![1](https://user-images.githubusercontent.com/15858973/120440034-b4af2f80-c372-11eb-92c5-fd96d6bdde03.png)
when search bar is disabled:
![2](https://user-images.githubusercontent.com/15858973/120440046-b7aa2000-c372-11eb-82be-bacbeeebcbe1.png)

thank you for building such a great theme!
and can you please fix this bug?

**Comment by Guerra24** [comment]
Should be fixed now, I don't use the search bar so it may break and I wouldn't notice right away.
