### ISSUE TITLE
Context menus not styled correctly on Linux

### ISSUE THREAD

**Issue by Tarballwalf** [Guerra24/Firefox-UWP-Style#29]
![Screenshot from 2021-06-03 12-33-59](https://user-images.githubusercontent.com/56345519/120623418-62503a80-c468-11eb-91fe-0b74eacdc26a.png)

**Comment by Guerra24** [comment]
I don't use desktop Linux so that entire use case has never been tested. I'm going to setup a VM to debug this.

**Comment by Guerra24** [comment]
Should behave a bit better now. I'm going to keep this open for tracking purposes as the context menus have more issues.

![image](https://user-images.githubusercontent.com/9023392/120705467-1a83e000-c475-11eb-89df-dfc6d3c77f00.png)
