### ISSUE TITLE
Notification Popups have a border

### ISSUE THREAD

**Issue by cole-h** [Guerra24/Firefox-UWP-Style#3]
As you can see, there is a black section lining the top and far right sides of the popup:

![image](https://user-images.githubusercontent.com/28582702/42478145-7996d736-8388-11e8-8e7e-d237eb6e0848.png)

This is due to

	#alertNotification {
		padding: 8px 16px 0px 0px !important;
	}

at line 531 in `pagesChrome.css`. By making them all `0px`, the box popup looks fine. Is there any way to completely remove the padding on the top and right side, so that it doesn't overlap the scrollbar?

**Comment by Guerra24** [comment]
The black background was caused by another rule that affected all windows that weren't the main one.
