### ISSUE TITLE
A problem with the startpage of Firefox

### ISSUE THREAD

**Issue by ghost** [Guerra24/Firefox-UWP-Style#34]
Hey, I'm having a problem in the default startpage of Firefox, the config button is incomplete. And, when I click on it, the buttons are too white.

OS: Windows 10
Firefox Version: 93.0

![screenshot](https://user-images.githubusercontent.com/87345663/136982905-9d64ee17-7ab7-4d69-96d9-94b47bd8f0b9.png)

![another-screenshot](https://user-images.githubusercontent.com/87345663/136983328-ca54cce9-05b7-4da8-a4fc-d77db872a12f.png)

**Comment by Guerra24** [comment]
Hello! The small settings button is getting fixed when #31 merges.

I tested with a clean profile and the buttons show up just fine. Are you sure the accent color is not forced to white?
![image](https://user-images.githubusercontent.com/9023392/136986503-4864543e-86cc-4b53-be84-41d12962f1da.png)

**Comment by ghost** [comment]
You mean in the chrome folder? I didn't change anything there.

**Comment by ghost** [comment]
I reinstalled the theme and still with this bug. It can be fixed if I change the accent color?

**Comment by Guerra24** [comment]
I mean in Windows, it uses the accent color you set in personalization -> colors in the settings app.

**Comment by ghost** [comment]
It's using the default for dark theme.

![screenshot](https://user-images.githubusercontent.com/87345663/137027373-8eba4c4a-a5e7-4e40-badd-b82e303fddf2.png)

**Comment by Guerra24** [comment]
What happens if you override it? Create a new string property in `about:config` with name `ui.-moz-accent-color` and value `#4C4A48`. Like this:
![image](https://user-images.githubusercontent.com/9023392/137029067-0a193e66-c358-4459-8615-07267d9187f7.png)

![image](https://user-images.githubusercontent.com/9023392/137028971-5a3fc7f0-6277-4be0-b24f-02e1f61041d6.png)

Then restart Firefox.

**Comment by ghost** [comment]
It didn't work :(

**Comment by Guerra24** [comment]
It works for me so I don't know what else could it be, sorry.

**Comment by ghost** [comment]
Ok, I'm going to make tests and see if I can fix. Thanks for the fast reply and thanks for the beautiful project, I never saw other firefoxcss like yours.
