### ISSUE TITLE
Content inside login autocomplete panel not showing

### ISSUE THREAD

**Issue by Gargantuan5k** [Guerra24/Firefox-UWP-Style#36]
![image](https://user-images.githubusercontent.com/73837135/138045731-bbfcd848-4478-44a3-83b0-a5e7e2519cdd.png)

Text inside the login panel isn't showing

**Comment by Guerra24** [comment]
Should be fixed in the latest commit of the `sun-valley` branch

**Comment by Gargantuan5k** [comment]
Thanks!
