### ISSUE TITLE
Add-on dialog box window is transparent

### ISSUE THREAD

**Issue by Gargantuan5k** [Guerra24/Firefox-UWP-Style#37]
![image](https://user-images.githubusercontent.com/73837135/138407349-a213b45a-9211-4021-95df-31a75e3df737.png)

**Comment by Gargantuan5k** [comment]
![WhatsApp Image 2021-10-22 at 15 00 31](https://user-images.githubusercontent.com/73837135/138430762-7e286efb-0c6c-45fc-8f1d-6ae60010f288.jpeg)
Similar issue with bookmark creation dialog

**Comment by Guerra24** [comment]
Fixing autocomplete panel is not the most straightforward thing to do, should be good now 😅 Please close this if that's the case otherwise let me know if something else broke.

**Comment by Gargantuan5k** [comment]
Tested it a bit, the issue is definitely fixed and I didn't see anything else broken so I'm closing this now :) (Will reopen if I encounter an issue later, thanks for fixing these issues so promptly)
