### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by tyeeman** [Guerra24/Firefox-UWP-Style#38]
I'm using FF portable v.88 and I followed the install instructions. When restarting FF my tabs are all dark except the one in view but my backgrounds of all pages are still all white. I'm on Win7 64bit. Any tips?

**Comment by Guerra24** [comment]
The theme has never been tested on Win7 or portable FF. The 89+ branch should work better since it has fixes for both Linux and macOS (which might also affect Win7), you should upgrade to a supported version regardless.

**Comment by Guerra24** [comment]
Closing because no more info was provided.
