### ISSUE TITLE
Bookmarks toolbar content issues

### ISSUE THREAD

**Issue by v1ruscan** [Guerra24/Firefox-UWP-Style#40]
Hi, the distance between the text and the icon in the bookmarks toolbar is too tight, can you fix it? I think they should look like picture 2.
![12141534](https://user-images.githubusercontent.com/96106970/145955068-2b0e6831-3ce8-44e9-a995-25700852d848.PNG)
![12141542](https://user-images.githubusercontent.com/96106970/145955085-5c19e0e1-8016-4758-92f0-87ee8630cf5b.PNG)

**Comment by Guerra24** [comment]
Should be fixed in the latest commit of `firefox-89` or `nightly`.
