### ISSUE TITLE
URL-bar suggestions have a non-alignment indicator

### ISSUE THREAD

**Issue by HuyHung1408** [Guerra24/Firefox-UWP-Style#41]
Best Firefox theme so far for me although there's bug as you can see.
![image](https://user-images.githubusercontent.com/86362423/147626090-2ab581b6-bc02-4b7e-b5ac-7509d05a1606.png)

**Comment by Guerra24** [comment]
Should be fixed in `nightly` or `firefox-89`.

https://user-images.githubusercontent.com/9023392/147866861-f78948a7-900a-4f4d-84be-cb5f72727893.mp4

**Comment by HuyHung1408** [comment]
Thanks!
