### ISSUE TITLE
Report extension buggy dialog

### ISSUE THREAD

**Issue by ghost** [Guerra24/Firefox-UWP-Style#46]
![image](https://user-images.githubusercontent.com/85873175/152629532-1e2a9212-c0a0-4de4-84c0-bf2e76c16881.png)

To reproduce the issue:
1. Click the hamburger menu > Add-ons and themes.
2. Click Extensions.
3. Click on the three dots menu on any of the installed extensions.
4. Click Report.

**Comment by Guerra24** [comment]
Just tested this and ngl I have no idea what is going on with this menu. I have not seen it break like this anywhere else.
