### ISSUE TITLE
Black Bar under Address Bar

### ISSUE THREAD

**Issue by lzlrd** [Guerra24/Firefox-UWP-Style#49]
There's a black bar underneath the address bar whether the bookmark bar is enabled or not:

![image](https://user-images.githubusercontent.com/24303423/158020413-5c429b1b-5f87-4290-a329-7e17a60139bd.png)

**Comment by Guerra24** [comment]
This is related to #39 I believe. The black bar is just margin added to allow the feature to work correctly and behave like default Firefox. Although I have never tested any forks so if Tor adds its own tweaks those might change the look and behavior.

**Comment by lzlrd** [comment]
> This is related to #39 I believe. The black bar is just margin added to allow the feature to work correctly and behave like default Firefox. Although I have never tested any forks so if Tor adds its own tweaks those might change the look and behavior.

That does seem to be the case, thanks. https://github.com/Guerra24/Firefox-UWP-Style/issues/50#issuecomment-1065938856 also helps to remove it.
