### ISSUE TITLE
No background color under search engine icons when navigating with keyboard

### ISSUE THREAD

**Issue by cinty8b** [Guerra24/Firefox-UWP-Style#5]
When searching in address bar and selecting among search engines with arrow keys, there's blue background in default style, but no obvious visual change in Firefox-UWP-Style.
![background color](https://user-images.githubusercontent.com/5980459/43834023-4a105e00-9b3f-11e8-8287-8c1aa0158927.jpg)
![background color without border](https://user-images.githubusercontent.com/5980459/43834040-5561fc96-9b3f-11e8-8144-f1eda6a53f0e.jpg)
both screenshots with Amazon selected

**Comment by Guerra24** [comment]
Fixed in latest commit.
![Fixed](https://puu.sh/BaScl/6822fe26eb.png)
