### ISSUE TITLE
Recent changes break autoscroll cursor

### ISSUE THREAD

**Issue by ghost** [Guerra24/Firefox-UWP-Style#58]
Middle-clicking the mouse to engage autoscroll should make the autoscroll mouse cursor appear - this one: 

![image](https://user-images.githubusercontent.com/58130821/167962767-9a6af0fb-88b6-4282-a5b3-4dc35b3b3ede.png)

Since the recent changes, this is just a transparent square.

**Comment by Guerra24** [comment]
Duplicate of #56
