### ISSUE TITLE
Context menu

### ISSUE THREAD

**Issue by Revnae** [Guerra24/Firefox-UWP-Style#59]
Hey is there anyway to just use the context menu theming of the style :D because i love the consistency but wanna use regular firefox themes

**Comment by Guerra24** [comment]
Hi, you will need to extract panel's css from [base.css](https://github.com/Guerra24/Firefox-UWP-Style/blob/nightly/css/base.css#L299), context menu's css from [context.css](https://github.com/Guerra24/Firefox-UWP-Style/blob/nightly/css/context.css) and finally grab the variables from the [style you want](https://github.com/Guerra24/Firefox-UWP-Style/tree/nightly/css/styles).
