### ISSUE TITLE
Sun Valley doesn't work

### ISSUE THREAD

**Issue by tevzselcan** [Guerra24/Firefox-UWP-Style#64]
The Sun Walley mode doesn't work for me, even thought its enabled in the about:config . But the rounded corners do work.
![neki](https://user-images.githubusercontent.com/82435930/176272723-4563d276-3000-4559-989f-387bc78c4dd3.png)

**Comment by Guerra24** [comment]
Hi. Would you mind giving more information? (screenshots, etc) I can't help with just that.

**Comment by tevzselcan** [comment]
I downloaded Firefox Nightly file and pasted the files exactly as it said. But when I try to enable the Sun Valley mode, it doesn't change anything even though it is enabled (looks like this still) 
![lol](https://user-images.githubusercontent.com/82435930/176363989-37a92883-7996-41b7-aabf-6a1ad7b80c26.png)
But I have enabled
 the rounded tabs, which do work.
![neki](https://user-images.githubusercontent.com/82435930/176364122-e8d39cb4-ae3d-4dcf-8743-caa7d93214a2.png)
I'm using Firefox latest version on a MacBook Pro M1

**Comment by Guerra24** [comment]
As far I can tell it looks to be working fine. Check if the settings page or library window have changed.

**Comment by tevzselcan** [comment]
The settings page looks like this
![image](https://user-images.githubusercontent.com/82435930/176462415-64f2c4b1-0083-462d-8130-c47ec9c20897.png)

**Comment by tevzselcan** [comment]
It indeed did change, but how do I get the same look as the one in the screenshots?

**Comment by Guerra24** [comment]
The only thing I see is that accent color is missing. To fix that switch to the correct version, in this case the 96-102 one.
