### ISSUE TITLE
transparent menu issue

### ISSUE THREAD

**Issue by iamhanix** [Guerra24/Firefox-UWP-Style#66]
![SCR-20220711-v](https://user-images.githubusercontent.com/47962934/178157527-fe5fb25b-8fc9-40b2-85f0-fbcdf433d5c3.png)
![SCR-20220711-2l](https://user-images.githubusercontent.com/47962934/178157571-60c91086-ae10-4f8c-b16e-819a26dbe19b.png)

**Comment by Guerra24** [comment]
Hi. Could you provide more information? (FF version, theme version, OS, etc...)

**Comment by iamhanix** [comment]
FF version: 102.0.1 (64-bit), Theme version: Latest one, OS: macOS Monterey 12.4

**Comment by iamhanix** [comment]
> ![SCR-20220711-v](https://user-images.githubusercontent.com/47962934/178157527-fe5fb25b-8fc9-40b2-85f0-fbcdf433d5c3.png) ![SCR-20220711-2l](https://user-images.githubusercontent.com/47962934/178157571-60c91086-ae10-4f8c-b16e-819a26dbe19b.png)

Was working properly in 99

**Comment by Guerra24** [comment]
macOS has bare minimum support, I have never tested it. I'll check on a Linux VM but if that works just fine the you will be out of luck since I don't own a macOS capable device.

**Comment by iamhanix** [comment]
> macOS has the bare minimum support, I have never tested it. I'll check on a Linux VM but if that works just fine the you will be out of luck since I don't own a macOS capable device.

That's ok

**Comment by Guerra24** [comment]
It did happen on Linux so I was able to fix it, please try again.

**Comment by iamhanix** [comment]
> It did happen on Linux so I was able to fix it, please try again.

thanks bro, Fixed!!
