### ISSUE TITLE
Is there a way to use only part of the whole style (question) ?

### ISSUE THREAD

**Issue by VitalSkib** [Guerra24/Firefox-UWP-Style#67]
Hi. 
I'm just wondering if it is possible to use only a certain part of the code from the entire style? 
I mean not using the whole style and all the settings, but only part, specifically only change all the backgrounds and leave the rest by default?
And if this is possible, then how can I do it and what part of the code do I need to safely isolate?
I just want to be sure that no part of the code that I don't use doesn't interfere and does not cause any conflict..

Let me explain, I really love your mod (theme) and use it, but I want to try to use Firefox as is, with everything by default, without any tweaks and extensions for some time.. 
And the only thing that is very annoying me is this purplish tint everywhere.
TIA

**Comment by Guerra24** [comment]
Hi. Not really possible, this theme is over 4 years old and even I don't know which rules still work, it just works and on top of that it was build as a full replacement so aside from context menus there is no proper way to isolate specific parts of the code, I think creating something from scratch is better and faster than trying to figure out where is everything set.

The colors are set as part of the styles so the only thing left is figuring out the selectors.

**Comment by VitalSkib** [comment]
Hi. 
OK, I see, thanks for the answer.  
(my question can be closed, I guess..)

**Comment by VitalSkib** [comment]
> _...so aside from context menus there is no proper way to isolate specific parts of the code,_

Oh, then what will be the easiest way to disable the context menu stylizing at least?
TIA

**Comment by Guerra24** [comment]
> Oh, then what will be the easiest way to disable the context menu stylizing at least?

Sorry for the very late reply. Just [comment out this](https://github.com/Guerra24/Firefox-UWP-Style/blob/nightly/userChrome.css#L8).

**Comment by VitalSkib** [comment]
> > Oh, then what will be the easiest way to disable the context menu stylizing at least?
> 
> Sorry for the very late reply. Just [comment out this](https://github.com/Guerra24/Firefox-UWP-Style/blob/nightly/userChrome.css#L8).

Yes, thanks. I figured it out myself already.. 👍
