### ISSUE TITLE
Top-Right button have some problem when I hover it 

### ISSUE THREAD

**Issue by kurisucat** [Guerra24/Firefox-UWP-Style#69]
![Top-Right button](https://user-images.githubusercontent.com/64016189/190674412-f2548dd0-539b-4462-ba63-41377421669a.png)

Just like this

PLZ fix it thanks.

**Comment by Guerra24** [comment]
Hi, are you using non-integer scaling?

**Comment by kurisucat** [comment]
> Hi, are you using non-integer scaling?

No, If you mean Windows Display Setting.

![Picture](https://user-images.githubusercontent.com/64016189/191940268-01499df7-92d3-4d92-848a-fc07f902766d.png)
