### ISSUE TITLE
"Developer Tools" Bar styles buttons but nothing else

### ISSUE THREAD

**Issue by Mrfiregem** [Guerra24/Firefox-UWP-Style#7]
This theme interferes with developer tools so that the buttons are styled when they weren't meant to be. Here's a picture of the Inspector showing what I mean;
![image](https://user-images.githubusercontent.com/5158194/43962509-d9bc5238-9c85-11e8-996d-a4d13bcc5538.png)
As you can see, the buttons are now dark, but still retain their black icons, making it look meesy and hard to see along with white gaps between this. This theme shouldn't modify the developer tools in my opinion, an exception being the scrollbars.

**Comment by Guerra24** [comment]
Dev tools have dark theme but doesn't follow the setting in Firefox. Is not easy to not style the tools, they're just an iframe in the browser without proper `@-moz-document` url.

Tried my best but if breaks other parts of the browser I would have to revert the changes.

If you find any other styled part, feel free to reopen.

**Comment by Guerra24** [comment]
Bad news... this breaks any other styled button. Gonna revert and meanwhile please use the dark themed tools.
