### ISSUE TITLE
Latest version does not inherit Windows accent color?

### ISSUE THREAD

**Issue by LarLei** [Guerra24/Firefox-UWP-Style#71]
Hello,

Thank you for making and maintaining this wonderful theme!

The theme file is (Firefox-UWP-Style-firefox-103.zip) downloading from https://github.com/Guerra24/Firefox-UWP-Style/archive/refs/heads/firefox-103.zip

Windows 10 Pro 64-bit Version 21H2 (OS Build 19044.2130)
Firefox 106.0.1 (64-bit)

Windows accent color is set - Start > Settings > Personalization > Colors > Choose your accent color
Firefox is set to use "System theme - Auto"

As you can see from the screen capture below, the theme inherits the accent color (i.e. lilac):
1. Line color above the tab
2. Enhanced Tracking Protection toggle switch
3. Bookmark (star)

![ff1](https://user-images.githubusercontent.com/76087721/197264351-f7b2afc5-3e89-4e71-b936-13e41ea7e156.png)

However, the theme does not inherit the accent color:

1. Color bar left of General option
2. Radio button
3. Check boxes
5. Text (i.e. What's new, Learn more)

![ff2](https://user-images.githubusercontent.com/76087721/197265231-eec49abe-abdd-4764-882c-55f1b92b01cf.png)

7. about:support

![ff3](https://user-images.githubusercontent.com/76087721/197265361-06936f2a-bc44-4923-a177-2ed9659b97d3.png)

9. Download status bar color

![ff4](https://user-images.githubusercontent.com/76087721/197265431-370f2f78-64d1-43d7-bec3-022a63f8a7b7.png)

Thanks,

**Comment by Guerra24** [comment]
Hi. So it turns out after a quick search the pref `widget.non-native-theme.use-theme-accent` was disabled on windows so the accent color defaulted to blue, you can toggle it back to restore the theme color. I didn't know about this so I'll be adding it in the readme.

**Comment by LarLei** [comment]
That's it!  Thanks so much for the quick response and resolution!
