### ISSUE TITLE
Gmail scroll bar is black.

### ISSUE THREAD

**Issue by zabarocky** [Guerra24/Firefox-UWP-Style#76]
![image](https://user-images.githubusercontent.com/85898484/228870392-216c85f9-6ecc-4c1d-82c4-02c0bdb55ff7.png)

Edit: Occurs on all pages

**Comment by Guerra24** [comment]
Hello, yes this is intended. If the website does not override the scrollbar colors, then the theme applies its own scheme. It is designed for websites that are theme-aware and follow the browser's theme status (dark or light) or have a matching dark/light theme. You can use something like [Stylus](https://addons.mozilla.org/en-US/firefox/addon/styl-us/) to override it.
