### ISSUE TITLE
White bar at the bottom of Library

### ISSUE THREAD

**Issue by kamez104** [Guerra24/Firefox-UWP-Style#80]
I don't know whether to take this up with you or the MicaForEveryone guys, but I just wanted to know if this is a common issue.

https://github.com/Guerra24/Firefox-UWP-Style/assets/138945522/a7139f54-6da7-4fa1-8acf-eaa267176b94

**Comment by Guerra24** [comment]
Hi, this is a known issue due to a bad interaction when mica and dcomp are enabled. You can temporarily fix it by disabling `gfx.webrender.dcomp-win.enabled`. It can only be fixed on Firefox's side.

**Comment by kamez104** [comment]
> Hi, this is a known issue due to a bad interaction when mica and dcomp are enabled. You can temporarily fix it by disabling `gfx.webrender.dcomp-win.enabled`. It can only be fixed on Firefox's side.

Thanks for the reply!

**Comment by Guerra24** [comment]
Closing, since the CSS properties used to get Mica working were removed from Firefox. It will work until 117 releases.
