### ISSUE TITLE
Question on "about:" pages and "Library" window tweaks

### ISSUE THREAD

**Issue by Zabooby** [Guerra24/Firefox-UWP-Style#83]
Could you point me to the parts of your code that is able to style the "about:" pages and "Library" window?

**Comment by Guerra24** [comment]
Hello!

For `about:` it's here: https://github.com/Guerra24/Firefox-UWP-Style/blob/nightly/css/pagesContent.css

And for Library and others is here: https://github.com/Guerra24/Firefox-UWP-Style/blob/nightly/css/pagesChrome.css

**Comment by Zabooby** [comment]
Thank you for the answer!

For Library are the relevant lines starting from [this ](https://github.com/Guerra24/Firefox-UWP-Style/blob/c0da33a40ebaae38789d53636696f57e4a3c870a/css/pagesChrome.css#L113C53-L113C53)line?

**Comment by Guerra24** [comment]
Yes, that is correct.

**Comment by Zabooby** [comment]
How do I change the background colour of boxes in about: pages 
![image](https://github.com/Guerra24/Firefox-UWP-Style/assets/78969986/ff73b109-7100-4ad2-9602-080714104d90)
![image](https://github.com/Guerra24/Firefox-UWP-Style/assets/78969986/a6e33503-3d80-4449-badb-214c56ae8296)

**Comment by Guerra24** [comment]
That depends on the element and page, you can use dev tools on those pages to see the HTML. For the language list it should be `#translations-manage-install-list`. For `about:support` those are just tables, the root `table` element has the background rules.

**Comment by Zabooby** [comment]
How do I find out what to put on the line above the element I'm trying to change? For example, would I use something like: 

```
:root {
#translations-manage-install-list
}
```

or 

```
@-moz-document url-prefix("about:") {
#translations-manage-install-list
}
```
or something else. 

Also how were you able to change the langauge list box, I couldn't find `#translations-manage-install-list` anywhere?

**Comment by Guerra24** [comment]
```css
@-moz-document url-prefix("about:preferences") {
    #translations-manage-install-list {
        /* rules here */
    }
}
```

Because I don't set it there, it pulls the background color from the `--in-content-box-background` variable and I just set that to transparent here https://github.com/Guerra24/Firefox-UWP-Style/blob/nightly/css/styles/sun-valley/pagesContent-dark.css#L12C58-L12C58.

The moz-document is there only to limit CSS to specific pages, just in case somewhere else there is another element with the same ID or class.

**Comment by Zabooby** [comment]
Ohh, thanks for the explanation, I get it now. 

One more question, is `@-moz-document url-prefix("chrome://"), regexp("about:(?!blank).*") {` the same as `@-moz-document url-prefix("about:") {` ?

**Comment by Guerra24** [comment]
No, the first one checks for either URLs starting with `chrome://` or any `about:` page except `about:blank`, the second one only checks if a URL starts with `about:`.

**Comment by Zabooby** [comment]
Thanks for answering all of my questions! 

Btw some of your tooltips don't match your theme:
![image](https://github.com/Guerra24/Firefox-UWP-Style/assets/78969986/d8de72cc-aa75-4fea-a82a-9fadfee64ae0)

You could add this [ag.css loader](https://github.com/Zabooby/firefox-config/blob/main/userChromeAgentAuthorSheetLoader.uc.js) and your [matching tooltips settings](https://github.com/Zabooby/firefox-config/blob/main/userChrome.ag.css) if you want.

**Comment by Guerra24** [comment]
Yeah... I'm aware JS loaders exist, but those require configuration and I want something that works out-of-the-box as-is, which so far does not exist.
