### ISSUE TITLE
Extension icon does not inherit Windows accent color?

### ISSUE THREAD

**Issue by LarLei** [Guerra24/Firefox-UWP-Style#84]
Hi,

Thank you for maintaining this awesome theme!

Extension - https://addons.mozilla.org/en-US/firefox/addon/traduzir-paginas-web/
Theme file - https://github.com/Guerra24/Firefox-UWP-Style/archive/refs/heads/firefox-120.zip
Windows 10 Pro 64-bit Version 22H2 (OS Build 19045.3693)
Firefox 120.0 (64-bit)

As you can see, the extension icon uses the default Firefox color (cyan).  I am not sure if this an extension issue or a minor theme issue.

![TWP](https://github.com/Guerra24/Firefox-UWP-Style/assets/76087721/f7ea8168-ae30-42c2-bfd0-d778a253bbf7)

Thanks,

**Comment by Guerra24** [comment]
Hello!

This is expected since the extension uses a custom image that cannot be styled, it would require custom support.

![image](https://github.com/Guerra24/Firefox-UWP-Style/assets/9023392/328cdfa4-6402-4b3f-b420-d960ba072108)

**Comment by LarLei** [comment]
Thanks for the quick response!
