### ISSUE TITLE
Radio buttons miss styled in about pages

### ISSUE THREAD

**Issue by sterno900** [Guerra24/Firefox-UWP-Style#85]
https://github.com/Guerra24/Firefox-UWP-Style/assets/50577964/7c682b5e-f4ce-40f3-adae-bc76aa203457

**Comment by sterno900** [comment]
I'm on 2560p with 150% DPI scaling.

**Comment by Guerra24** [comment]
Hello!

Looks like style selectors changed in 122. I will take a look next weekend.
